//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcInlämningsuppgift2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Kund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kund()
        {
            this.Bestallnings = new HashSet<Bestallning>();
        }
    
        public int KundID { get; set; }

        [Required(ErrorMessage ="Ange Namn")]
        public string Namn { get; set; }

        [Required(ErrorMessage = "Ange Gatuadress")]
        public string Gatuadress { get; set; }

        [Required(ErrorMessage = "Ange Postnr")]
        public string Postnr { get; set; }

        [Required(ErrorMessage = "Ange Postort")]
        public string Postort { get; set; }

        [Required(ErrorMessage = "Ange Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Ange Telefon")]
        public string Telefon { get; set; }

        [Required(ErrorMessage = "Ange AnvandarNamn")]
        public string AnvandarNamn { get; set; }

        [Required(ErrorMessage = "Ange Losenord")]
        public string Losenord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestallning> Bestallnings { get; set; }
    }
}
